Add database
Christina1407/java-filmorate pull request #4
Opened 2023-07-20 17:28 UTC by Christina1407

2023-07-22 12:42 UTC, litvitnik commented on src/main/java/ru/yandex/practicum/filmorate/model/dto/RatingMpaDto.java
> +//Сделано из-за дефиса в рейтинге MPA, так как в enum нельзя его поставить
Пока не могу понять, какие нам это накладывает ограничение. Мы же можем просто добавить в EnumMPA такой же метод по получению ENUM из String(который в конструкторе у этого MPA) и получим такой же функционал. Или пришлось столкнуться с каким-то более серьезным ограничением?

2023-07-22 12:46 UTC, litvitnik commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/FilmDbStorage.java
> +                    String sqlQueryFilmGenres = "select * from \"genre\" where genre_id in (select genre_id from \"film_genre\" where film_id = :film_id)";
Я бы предложил все таки воспользоваться механизмом batchUpdate() здесь. Насколько я помню, он не является обязательным в этой работе, но дальше это будет требоваться. Хотя дальше за нас работа с базой автоматически будет выполняться :)
Вообще, в любом случае я рекомендую обратить внимание на этот механизм и попробовать его использовать - потому что он является ключевым в разработке высоконагруженных приложений. А любое приложение всегда имеет риск стать резко высоконагруженным в два часа ночи в какой-нибудь особый день :D 
Однажды использовав только этот механизм и ничего больше я сократил время выгрузки недельного отчета для AdTech компании в США с двух с половиной часов до трех минут. Поэтому, я думаю, знать такой механизм, а особенно иметь возможность рассказать о таком на собеседовании будет невероятно полезно! Ну и если без занудства, то всегда при работе с БД следует избегать походов в базу данных в цикле, потому что создавать по одному подключению на каждый элемент в коллекции(а их бывает тысячи, когда подключений, скажем, единицы или десятки). Вот как-то так :)

2023-07-22 12:47 UTC, litvitnik commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
Либо в этом файле не та кодировка, либо строка в любом случае не нужна в конфигурации

2023-07-22 12:48 UTC, litvitnik commented on src/main/resources/schema.sql
> +    email     varchar(100) not null,
Имейлы бывают и длиннее. Если интересно - https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address#:~:text=%22There%20is%20a%20length%20limit,total%20length%20of%20320%20characters.

2023-07-22 12:49 UTC, litvitnik commented on src/main/resources/schema.sql
> +    name     varchar(50) not null,
Названия фильмов зачастую сильно длиннее. Например - Ля Комедия 2, или Совсем другая история с элементами большого искусства

2023-07-22 12:50 UTC, litvitnik commented on src/main/resources/schema.sql
> +    description   varchar(200),
Я бы предложил задать под описание хотя бы 500-1000 символов. А то получится какой-нибудь твиттер :D

2023-07-22 12:50 UTC, litvitnik commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/db/FilmDbStorageTest.java
> +
Отдельно хочу отметить, что очень хорошие и полные тесты!

2023-07-22 12:51 UTC, litvitnik requested changes
Требуются лишь незначительные изменения, отписал по каждому из них в комментариях :)

2023-07-22 14:31 UTC, Christina1407 commented on src/main/java/ru/yandex/practicum/filmorate/model/dto/RatingMpaDto.java
> +//Сделано из-за дефиса в рейтинге MPA, так как в enum нельзя его поставить
В модели RatingMPA в поле name лежит enum EnumMPA, который при сериализации превращается в строку, например PG_13, а в тестах должно быть PG-13, при этом назвать объект енама PG-13 и использовать name из скобок  PG_13("PG-13") не получилось, поэтому сделала через DTO.

2023-07-22 14:42 UTC, Christina1407 commented on src/main/resources/schema.sql
> +    description   varchar(200),
В ТЗ спринта №9 было это ограничение, поэтому и в базу такое поставила
![2023-07-22_17-38](https://github.com/Christina1407/java-filmorate/assets/123633941/555d4865-1d18-48f5-a16f-8d35f68d97d9)

2023-07-22 15:10 UTC, Christina1407 commented on src/main/resources/schema.sql
> +    name     varchar(50) not null,
исправила

2023-07-22 15:12 UTC, Christina1407 commented on src/main/resources/schema.sql
> +    email     varchar(100) not null,
Исправила на 254

2023-07-22 15:13 UTC, Christina1407 commented on src/main/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
Удалила

2023-07-22 20:40 UTC, Christina1407 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/db/FilmDbStorage.java
> +                    String sqlQueryFilmGenres = "select * from \"genre\" where genre_id in (select genre_id from \"film_genre\" where film_id = :film_id)";
Не совсем поняла, как использовать batchUpdate(), так как здесь выполнялся select из базы. Замечание учла: Обращения в цикле к базе убрала, batchUpdate() применила в методе insertIntoFilmGenres в классе FilmGenreDbStorage. enrichFilmGenres перенесла в класс FilmServiceImpl

2023-07-23 17:43 UTC, litvitnik commented on src/main/java/ru/yandex/practicum/filmorate/model/dto/RatingMpaDto.java
> +//Сделано из-за дефиса в рейтинге MPA, так как в enum нельзя его поставить
Для этих целей отлично подойдут методы из этой статьи:
https://www.baeldung.com/jackson-serialize-enums

2023-07-23 17:45 UTC, litvitnik commented on src/main/resources/schema.sql
> +    email     varchar(100) not null,
Должно быть 320

2023-07-23 17:46 UTC, litvitnik commented on src/main/resources/schema.sql
> +    description   varchar(200),
Забыл про этот пункт в ТЗ. Спасибо! Ты молодец, что не забыла про него

2023-07-23 19:17 UTC, Christina1407 commented on src/main/resources/schema.sql
> +    email     varchar(100) not null,
ок

2023-07-23 19:30 UTC, Christina1407 commented on src/main/java/ru/yandex/practicum/filmorate/model/dto/RatingMpaDto.java
> +//Сделано из-за дефиса в рейтинге MPA, так как в enum нельзя его поставить
Получилось, спасибо)

2023-07-23 19:53 UTC, litvitnik commented on src/main/resources/schema.sql
> +    email     varchar(100) not null,
Там просто 64 перед собачкой, 255 после собачки, ну и сама собачка еще :)

2023-07-23 19:53 UTC, litvitnik commented on src/main/java/ru/yandex/practicum/filmorate/model/dto/RatingMpaDto.java
> +//Сделано из-за дефиса в рейтинге MPA, так как в enum нельзя его поставить
Отлично, рад, что у тебя это получилось :)

2023-07-23 19:54 UTC, litvitnik approved these changes
+

2023-07-25 13:36 UTC, merged